version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./app:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8086:80"
    depends_on:
      - app
    container_name: pr_nginx

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./app:/var/www/
    depends_on:
      - db
    container_name: pr_app

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: pr_redis

  db:
    image: mariadb
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: parser
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8182:3306
    container_name: pr_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8092:80"
    container_name: pr_myadmin

  test_db:
    image: mariadb
    environment:
      MYSQL_DATABASE: pr_test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8012:3306
    container_name: pr_test_db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: pr_rabbitmq